### PR TITLE
#571 remove restrictions that prevented building some cat pages

### PR DESCRIPTION
**Pull request by dmcassel**
Category pages that have subcategories weren't getting built. This was
on purpose, but we no longer want it that way.

### CODE REVIEW

**Comment by dmcassel** [comment]
@gfurbush @kcoleman-marklogic This PR fixes the category/subcategory problem. Could you help me with testing to make sure it doesn't mess up anything else?

**Comment by kcoleman-marklogic** [comment]
Yes, I'll see what I can do. We're quite a few checkins behind master so I'll need to sort that first. Stay tuned.

**Comment by kcoleman-marklogic** [comment]
I pulled this (locally) on to the docapp branch for testing on pubs. I see 2 sorta-problems so far:

(1) Function lists are being generated for the category page even when there are subcats. 

I don't think this is a good idea. The main reason these function sets have subcats is that they're too big to consume at glance. I could be talked out of this position, though. At least temporarily. :)

Something isn't right with the sem landing page, (http://pubs.marklogic.com:8011/9.0/js/sem/semantics).

(2) It has no subcats (and isn't supposed to), but the text on the landing page has changed. It is a weird hack of a category that combines builtins and library funcs, so it is unsurprising that is would be trouble. 

This might be a content issue, though. I will look into it further and let you know.

**Comment by dmcassel** [comment]
Thanks @kcoleman-marklogic, I'll take a look at those two items.

**Comment by kcoleman-marklogic** [comment]
I noticed yesterday that the Search category has landing page content that is drawn from the subcategory of the same name. There was no summary for the top level, so I added one, but it is still being ignored in favor of the subcat summary. Possibly, what I added doesn't match the logic you expect. 

The related raw input file is pubs/raw/apidoc/SearchBuiltins.xml. The unadorned `<apidoc:summary>` element at the top is what I added. The one that looks like this is what is showing up in its place:
```
</apidoc:summary><apidoc:summary access="public" category="SearchBuiltins" subcategory="Search" lib="cts">
```

**Comment by kcoleman-marklogic** [comment]
Here's another issue for you:

Sometimes, the summary content for subcat landing pages is entirely omitted in the SJS apidoc. For example, contrast these:
- http://pubs.marklogic.com:8011/9.0/js/geo/geo (no summary content showing)
- http://docs-ea.marklogic.com/js/geo/geo (the equiv SJS page w/o the pull req active)
- http://pubs.marklogic.com:8011/9.0/geo/geo (the equiv XQuery landing page w the pull req active)

All the other subcats in that category manifest the same behavior. It isn't just cats with subcats, either. The Redaction (rdt) category has the same issue. On the other hand, the thesaurus cat is fine (http://pubs.marklogic.com:8011/9.0/js/thsr).

I think it might be happening in places where there are separate summaries for the same cat/subcat for xquery and javascript. e.g. `<apidoc:summary ... class="xquery"/>` vs <apidoc:summary ... class="javascript"/>`.

It's probably OK to assert you can't do this, but (a) it used to work, and (b) we need to know definitively if it's now unsupported so we can change the content to match what the app expects.

**Comment by dmcassel** [comment]
Findings from @jmckean17: 

I’m looking at the Semantics landing page, and it has changed a bit with the new configuration. Previously the landing page had this content:
 
> sem functions (Semantics)
>  
> The semantic functions include functions that are built into MarkLogic Server as well as functions that are implemented in an XQuery library.
>  
> To use the semantics XQuery library module as part of your own XQuery module, include the following line in your XQuery prolog:
>  
> import module namespace sem = "http://marklogic.com/semantics"
       at "/MarkLogic/semantics.xqy";
>  
> The library namespace prefix sem is predefined in the server.
>  
> The rdf functions are built-in functions to construct and use rdf:langString types. The rdf namespace prefix is built into the server.
>  
> &lt;followed by table of functions&gt;
 
And now the landing page just contains this:
 
> sem functions (Semantics)
>  
> The rdf functions are built-in functions to construct and use rdf:langString types. The rdf namespace prefix is built into the server.
>  
> &lt;followed by table of functions&gt;
 
So some information got lost somewhere. I don’t know enough about this to know where the content went or how to fix it.
 
Also, at the bottom of the new list, this function snuck in - sql:collatedString-collation
Curious…

**Comment by dmcassel** [comment]
@kcoleman-marklogic @jmckean17 I looked into the Semantics page and it looks like a content issue to me. In MarkLogic_9_pubs.zip, we have /pubs/raw/apidoc/semantics.xml with this:

    <apidoc:module name="semantics" category="Semantics" 
      xmlns:apidoc="http://marklogic.com/xdmp/apidoc" 
      xmlns="http://www.w3.org/1999/xhtml" lib="sem">
      <apidoc:summary category="Semantics">
        <p>The semantic functions include functions that are built into MarkLogic Server as well as functions that are implemented in an XQuery library.
        </p>
        <p>To use the semantics XQuery library module as part of your own XQuery module, include the following line in your XQuery prolog:
        </p>

Over in /pubs/raw/apidoc/SPARQL.xml, we have:

    <apidoc:module name="Extensions" category="Semantics" lib="rdf" xmlns:apidoc="http://marklogic.com/xdmp/apidoc"><apidoc:summary category="Semantics" lib="rdf">
      <p xmlns="http://www.w3.org/1999/xhtml">The rdf functions are built-in functions to construct and use
      rdf:langString types. The <code>rdf</code> namespace prefix is built into the server.</p>

So we have two &lt;apidoc:module&gt; entries with the same category attribute. I had to modify the code to avoid grabbing subcategory content (my first try displayed the text for a category and all subcategories). 

I'd like to call this a content problem. If it's a big problem to fix, let me know and I'll take another look, but at least we know what's going on now.

**Comment by kcoleman-marklogic** [comment]
We'll do some experiments next week to see if removing one of the summaries fixes the semantics problem. We may find that it does not just because there's special code in the app to handle this specific category. Will update with what we find.

**Comment by kcoleman-marklogic** [comment]
@dmcassel Your most recent checkin looks to have addressed the problem with the missing content on some of the SJS landing pages. Jane and I are going to test out some changes for the semantics problem today as well, as you suggested earlier.

**Comment by kcoleman-marklogic** [comment]
Here's a content organization issue we have, which may require changes to both the content and the app to address:

The summary for a category or sub-category is always a child of an apidoc:module. When there is just a category, but no sub-categories, then apidoc:module/apidoc:summary is the no-brainer content to use.

When there are subcategories, however, where should the category summary come from? Of necessity, it must be a child of an apidoc:module, but the module is going to be a subcategory's module, generally speaking.

Right now, it appears as if the category landing page content is a random (first?) subcat summary, even if there is an apidoc:summary for just the category. (That is, has `apidoc:summary/@category`, but no `apidoc:summary/@subcategory`).

Is there a different structure that would work better with the app? Does the app need different logic to select the proper summary?

**Comment by dmcassel** [comment]
I don't believe it's random or first -- I think it's applying logic to look for a category attribute, but no subcategory. Current logic:

    let $summaries-with-category :=
      ($raw-modules/apidoc:summary
        [@category eq $cat]
        [not($subcat) or @subcategory eq $subcat]
        [not(@class) or @class eq $mode]
      )[1]

So when there are subcategories, don't select their summaries for the category. Are you seeing cases where that's not working?

**Comment by kcoleman-marklogic** [comment]
OK, I think I understand what's happening now. What caused my previous comment was the observation that the landing page for the Search builtins (cts:*) and the landing page for the Search library modules (search:*) had the same content.

I now realize that the problem is more fundamental: They don't just have the same content. They are the same page (http://pubs.marklogic.com:8011/9.0/search). 

To work around this, we probably need to change one of the category names, much like we have Admin (the builtins) and Admin Library (the lib modules) already. I will try that today.

**Comment by kcoleman-marklogic** [comment]
Nope, changing the category name changed the text in the TOC, but not the URL. I tried using admin/admin library as a breadcrumb, but can't find anywhere that is special cased or specified in the config files. 

I tried adding an entry to `src/apidoc/config/category-mappings.xml` (even though admin seems to require no such thing), but that didn't make any difference, either.

I'm not sure what other rocks to look under. Do you have any ideas?

**Comment by dmcassel** [comment]
There are some cases where built-ins and libraries have the same URL, which means they display the same content.

> /9.0/search

That URL shows up under built-ins and libraries. Check what the source XML for each should be; check logic for determining URL.

**Comment by kcoleman-marklogic** [comment]
We're working around some of the semantic function issues by splitting them into subcats. This necessitates removing at least one line of special case text from toc.xqm (yay!). This gets rid of tacking "(sem:) or (sem.) on to the end of the main category title in the TOC.

Not sure of proper protocol for this since you already have a change set going. The line to be yanked is [this one](https://github.com/marklogic/RunDMC/blob/fb5a1b22d12ef94e9bc76195bbfed810fcafbdbe/src/apidoc/setup/toc.xqm#L237).

**Comment by dmcassel** [comment]
@kcoleman-marklogic I just pushed a commit to the PR that removes that line

**Comment by kcoleman-marklogic** [comment]
I think `toc:get-summary-for-category` has some faulty logic. Not new faulty logic, but rather roads untaken before we made this change. 

If it finds multiple summaries for a category, it arbitrarily picks the first one. That might be fine IF it paid attention to whether or not the summaries under consideration have subcategories. Consider what happens with [this code](https://github.com/marklogic/RunDMC/blob/fb5a1b22d12ef94e9bc76195bbfed810fcafbdbe/src/apidoc/setup/toc.xqm#L316-L321) if subcat is empty (as is the case for a main category summary), but the first summary on the list with a matching category turns out to be a subcat summary. You end up displaying the subcat summary on the main cat page.
```
  let $summaries-with-category :=
    ($raw-modules/apidoc:summary
      [@category eq $cat]
      [not($subcat) or @subcategory eq $subcat]
      [not(@class) or @class eq $mode]
    )[1]
```
If no subcat name was passed into the function, then it should probably be ignoring any and all subcat summaries. Something like `[(not($subcat) and not(exists(@subcategory))) or @subcategory eq $subcat]`. (Sorry, that's just a quick & dirty hack.)

I think I can work around this by ensuring that no subcat summary ever appears before a main cat summary, but I don't like depending on ordering like that.

I think that the subsequent code for identifying modules that contain summaries when `$summaries-with-category` finds nothing, has a somewhat similar problem. My observation is that, instead of matching no modules and falling through to the boilerplate code path, it concatenates all the summaries from all the subcats. For an example of this, see the CPF Functions landing page on pubs.

I think I can workaround this bug by ensuring that every main cat with subcats has an explicitly categorized summary.

**Comment by dmcassel** [comment]
I think I just made a typo in the code there. Should be:

    let $summaries-with-category :=
      ($raw-modules/apidoc:summary
        [@category eq $cat]
        [not(@subcategory) or @subcategory eq $subcat]
        [not(@class) or @class eq $mode]
      )[1]

That is, `not(@subcategory)` rather than `not($subcat)`.

**Comment by kcoleman-marklogic** [comment]
I don't think that's sufficient. That causes the subcat pages to use the main cat content because the main cat `apidoc:summary` elems will always satsify `not(@subcategory)`. You could probably do something like `not($subcat) and not(@subcategory)`.

**Comment by dmcassel** [comment]
Okay. I'll write some unit tests to make sure I'm capturing the desired results, then update the code.

**Comment by kcoleman-marklogic** [comment]
Here's another problem: The code that used to generate landing page content from `apidoc:object` elements isn't any longer. Contrast [this page](http://docs.marklogic.com/js/CharacterData) on docs.marklogic.com with the equivalent page on pubs.

I don't care that "The table below..." blah blah is gone, but it matters that the "X is a subtype of Y" type info (which is generated by the app) is gone. 

The code that used to do this is [here](https://github.com/marklogic/RunDMC/blob/2c6a7f413fad8df29cbe5af83f6f16bcb9eaedb7/src/apidoc/setup/toc.xqm#L408-L449). I tried to grok why it doesn't fire any longer, but failed.

**Comment by dmcassel** [comment]
@kcoleman-marklogic regarding the category summaries, I just consolidated the summary-gathering logic into a function and wrote some unit tests for it. Could you help me identify a case that doesn't work? (See src/test/apidoc-toc.xqy in the PR.)

**Comment by kcoleman-marklogic** [comment]
This rather violently did not work. It coughed up an XDMP-AS when I pulled in the change and reloaded pubs. I will dig further to make sure it's not UBD on my part. Here's a few frames worth of the error details. (I lopped off the timestamp, etc. to reduce the insanity.)
```
 [apidoc/setup/toc:toc] Creating new TOC at /media/apiTOC/9.0/toc.xml
 XDMP-AS: (err:XPTY0004) toc:find-primary-summary($raw-modules, $cat, $subcat, $mode) -- Invalid coercion: (fn:doc("/9.0/apidoc/Antenna.xml")/apidoc:module/apidoc:summary, fn:doc("/9.0/apidoc/ISYS.xml")/apidoc:module/apidoc:summary, fn:doc("/9.0/apidoc/Iceni.xml")/apidoc:module/apidoc:summary, ...) as element(apidoc:summary)?
 in /apidoc/setup/toc.xqm, at 316:5,
 in toc:find-primary-summary((fn:doc("/9.0/apidoc/Extension.xml")/apidoc:module, fn:doc("/9.0/apidoc/TraceBuiltins.xml")/apidoc:module, fn:doc("/9.0/apidoc/plugin.xml")/apidoc:module, ...), "Document Conversion", (), "javascript") [1.0-ml]
   $raw-modules = (fn:doc("/9.0/apidoc/Extension.xml")/apidoc:module, fn:doc("/9.0/apidoc/TraceBuiltins.xml")/apidoc:module, fn:doc("/9.0/apidoc/plugin.xml")/apidoc:module, ...)
   $cat = "Document Conversion"
   $subcat = ()
   $mode = "javascript"
 in /apidoc/setup/toc.xqm, at 343:4,
 in toc:get-summary-for-category("9.0", "javascript", (), "Document Conversion", (), "xdmp") [1.0-ml]
   $version = "9.0"
   $mode = "javascript"
   $prefixes-not-builtin = ()
   $cat = "Document Conversion"
   $subcat = ()
   $lib = "xdmp"
   $raw-modules = (fn:doc("/9.0/apidoc/Extension.xml")/apidoc:module, fn:doc("/9.0/apidoc/TraceBuiltins.xml")/apidoc:module, fn:doc("/9.0/apidoc/plugin.xml")/apidoc:module, ...)
 in /apidoc/setup/toc.xqm, at 1516:12,
 in toc:functions-by-category("9.0", "javascript", map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="CATSUBCAT"><map:value><map:map><map:entry key="S...</map:map>), (), "js_MarkLogicBuilt-InFunctions", "Document Conversion", fn:false(), (fn:doc("/apidoc/9.0/xdmp.powerpointConvert.xml")/api:function-page/api:function, fn:doc("/apidoc/9.0/xdmp.documentFilter.xml")/api:function-page/api:function, fn:doc("/apidoc/9.0/xdmp.zipManifest.xml")/api:function-page/api:function, ...)) [1.0-ml]
   $version = "9.0"
   $mode = "javascript"
   $m-mode-functions = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="CATSUBCAT"><map:value><map:map><map:entry key="S...</map:map>)
   $prefixes-not-builtin = ()
   $bucket-id = "js_MarkLogicBuilt-InFunctions"
   $cat = "Document Conversion"
   $is-REST = fn:false()
   $in-this-category = (fn:doc("/apidoc/9.0/xdmp.powerpointConvert.xml")/api:function-page/api:function, fn:doc("/apidoc/9.0/xdmp.documentFilter.xml")/api:function-page/api:function, fn:doc("/apidoc/9.0/xdmp.zipManifest.xml")/api:function-page/api:function, ...)
   $single-lib-for-category = "xdmp"
   $is-exhaustive = fn:false()
   $sub-categories = ()
   $href = "/js/xdmp/conversion"
 in /apidoc/setup/toc.xqm, at 1574:13,
 in toc:functions-by-bucket("9.0", "javascript", map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="CATSUBCAT"><map:value><map:map><map:entry key="S...</map:map>), ()) [1.0-ml]
   $version = "9.0"
   $mode = "javascript"
   $m-mode-functions = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="CATSUBCAT"><map:value><map:map><map:entry key="S...</map:map>)
   $prefixes-not-builtin = ()
   $forced-order = ("MarkLogic Built-In Functions", "XQuery Library Modules", "CPF Functions", ...)
   $m-buckets = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="MarkLogic Built-In Functions"><map:value><map:ma...</map:map>)
   $b = "MarkLogic Built-In Functions"
   $bucket-id = "js_MarkLogicBuilt-InFunctions"
   $is-REST = fn:false()
   $m-cats = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="Document Object"><map:value><api:function mode="...</map:map>)
   $cat = "Document Conversion"
 in /apidoc/setup/toc.xqm, at 1831:50,
 in toc:function-reference-node("9.0", map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="xquery"><map:value><map:map><map:entry key="CATS...</map:map>), fn:doc("/apidoc/9.0/document-list.xml")/apidoc:docs/apidoc:group[1]/apidoc:entry[1]) [1.0-ml]
   $version = "9.0"
   $m-functions = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="xquery"><map:value><map:map><map:entry key="CATS...</map:map>)
   $entry = fn:doc("/apidoc/9.0/document-list.xml")/apidoc:docs/apidoc:group[1]/apidoc:entry[1]
   $mode = "javascript"
   $mode-libs = (<api:lib mode="javascript" built-in="true" category-bucket="MarkLogic Built-In Functions" xmlns:api="http://marklogic.com/rundmc/api">AccessPlan</api:lib>, <api:lib mode="javascript" built-in="true" category-bucket="JavaScript Library Modules" xmlns:api="http://marklogic.com/rundmc/api">alert</api:lib>, <api:lib mode="javascript" built-in="true" category-bucket="MarkLogic Built-In Functions" xmlns:api="http://marklogic.com/rundmc/api">ArrayNode</api:lib>, ...)
   $prefixes-not-builtin = ()
 $m-mode-functions = map:map(<map:map xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:map="http://marklogic.com/xdmp/map"><map:entry key="CATSUBCAT"><map:value><map:map><map:entry key="S...</map:map>)
 in /apidoc/setup/toc.xqm, at 1890:35,

```

**Comment by dmcassel** [comment]
Yeah, sorry about that. Realized the error, will push up.

**Comment by kcoleman-marklogic** [comment]
Well, it did not explode. :) We are checking the results now.

**Comment by kcoleman-marklogic** [comment]
Well, as the old saying goes: I have some good news and some bad news.

The good news is that CharacterData and its cohort have been returned to their former glory. The bad news is all the main categories with subcat (the ones we started down this trail on behalf of) are throwing 404s. These guys:
```
SJS

http://pubs.marklogic.com:8011/9.0/js/extension
http://pubs.marklogic.com:8011/9.0/js/search
http://pubs.marklogic.com:8011/9.0/js/semantics
http://pubs.marklogic.com:8011/9.0/cpf-functions
http://pubs.marklogic.com:8011/9.0/js/geospatial-supporting-functions
http://pubs.marklogic.com:8011/9.0/js/javascript-search-(jsearch)
http://pubs.marklogic.com:8011/9.0/js/optic

XQuery

http://pubs.marklogic.com:8011/9.0/extension
http://pubs.marklogic.com:8011/9.0/semantics
http://pubs.marklogic.com:8011/9.0/cpf-functions
http://pubs.marklogic.com:8011/9.0/dls/library-services
http://pubs.marklogic.com:8011/9.0/modular-documents
http://pubs.marklogic.com:8011/9.0/search-library
```
The clever reader will note that these two lists are not symmetric. Search, being truly comitted to special snowflakeness, is working for XQuery, but not JS. (The builtins, that is. The Search API lib module is 404'ing for XQuery. It doesn't apply to the JS func list, so its absence there is correct.)

Optic also 404's in JS but not XQuery. However, there's not really a way for you to look at optic outside of pubs because we're running a special hack to generate XQuery docs for Optic.

I'm going to revert pubs to the docapp HEAD for a day so that we can give the 8.0-6 docs a final once-over without any false positives. I'll restore this pull req after we've completed our release check (and there's another update to this pull req).

**Comment by gfurbush** [comment]
Oy

**Comment by dmcassel** [comment]
It looks like all the examples you gave above, except for DLS and the XQuery Search library, have something in common: multiple library prefixes. Not sure how key that is, but I'll investigate.

**Comment by dmcassel** [comment]
DMC is intended to be replatformed, which will likely happen before I get around to folding in this change.

**Pull request closed without merging**
